HW02 unpack string is complete
IvanSkripnikov/otus_go_homework pull request #2
Opened 2023-08-30 19:38 UTC by IvanSkripnikov

2023-09-01 08:35 UTC, vladislavmass requested changes
Отличное начало. Код может работать с однобайтовой кодировкой, но как только будет дан текст с многобайтовой кодировкой начнутся проблемы. Для примеры рекомендую сделать тесткейс с кирилицей

2023-09-01 09:59 UTC, IvanSkripnikov commented
> Отличное начало. Код может работать с однобайтовой кодировкой, но как только будет дан текст с многобайтовой кодировкой начнутся проблемы. Для примеры рекомендую сделать тесткейс с кирилицей

а каким образом разбить по многобайтовой кодировке? Я думал index, symbol := range sa с этим справляется? или нужен другой механизм?

2023-09-01 16:27 UTC, IvanSkripnikov commented
> Отличное начало. Код может работать с однобайтовой кодировкой, но как только будет дан текст с многобайтовой кодировкой начнутся проблемы. Для примеры рекомендую сделать тесткейс с кирилицей

Добавил тесты с кириллицей и иероглифами - проходят)

2023-09-02 09:31 UTC, vladislavmass requested changes
Решение стало уже лучше, но оно не проходит следующий тест-кейс`{input: "a\t2b3c4", expected: "aa\t\tbcccc"},` А также в коде проблемы с разбиением на методы. Например почему метод `isErrorDigitSymbol` принимает число и слайс, когда по логике должен принимать `rune`. Схожая проблема наблюдается и в методе ` isErrorString`

2023-09-03 15:54 UTC, IvanSkripnikov commented
> Решение стало уже лучше, но оно не проходит следующий тест-кейс`{input: "a\t2b3c4", expected: "aa\t\tbcccc"},` А также в коде проблемы с разбиением на методы. Например почему метод `isErrorDigitSymbol` принимает число и слайс, когда по логике должен принимать `rune`. Схожая проблема наблюдается и в методе ` isErrorString`

Поправил, произвёл рефакторинг, добавил тесты

2023-09-03 16:52 UTC, vladislavmass requested changes
Тут однозначно перечислены не все escape символы. Полный их список есть по вот этой [ссылке.]( https://learn.microsoft.com/ru-ru/dotnet/standard/base-types/character-escapes-in-regular-expressions?redirectedfrom=MSDN) Но я бы вам советовал бы обратить внимание на `unicode.IsControl`

2023-09-06 04:38 UTC, vladislavmass requested changes
Стало намного лучше. Но все еще есть проблемы при обработке тест кейса `{input: "aa🔥0b", expected: "aab"},`

2023-09-06 04:38 UTC, hungry-honeybadger commented on hw02_unpack_string/unpack.go
> +	sa := []rune(s)
Очень сложно понять имя это переменной и в большом коде это вызовет много проблем.

2023-09-06 04:38 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	lenString := utf8.RuneCountInString(s)
Если тут будет 0, то зачем делать все остальные действия?

2023-09-06 04:38 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +func isErrorManyDigits(symbol rune, index int, s string) bool {
Сигнатура функции не соответствует ее назначению. Сигнатура этой функции должна выглядеть либо так
`func isErrorManyDigits(symbol, symbol2 rune) bool` или
`func isErrorManyDigits(symbols ...rune) bool`

2023-09-06 04:38 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		if isErrorUnknownChar(symbol) || isErrorManyDigits(symbol, index, s) {
Ошибка `isErrorUnknownChar`  некорректна. Могут быть использованы любые символы. Поэтому код непроходит следующий тест кейс `{input: "aa🔥0b", expected: "aab"},`

2023-09-06 07:03 UTC, IvanSkripnikov commented on hw02_unpack_string/unpack.go
> +	sa := []rune(s)
поправил

2023-09-06 07:03 UTC, IvanSkripnikov commented on hw02_unpack_string/unpack.go
> +	lenString := utf8.RuneCountInString(s)
поправил

2023-09-06 07:03 UTC, IvanSkripnikov commented on hw02_unpack_string/unpack.go
> +func isErrorManyDigits(symbol rune, index int, s string) bool {
поправил

2023-09-06 07:04 UTC, IvanSkripnikov commented on hw02_unpack_string/unpack.go
> +		if isErrorUnknownChar(symbol) || isErrorManyDigits(symbol, index, s) {
поправил

2023-09-07 09:04 UTC, vladislavmass approved these changes
Хорошая работа. Принято. 9/10. -1 баз за объявление рун через адресацию строк

2023-09-07 09:04 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	zeroRune         = rune("0"[0])
Руны в go определяются с помощью символа ''

2023-09-07 20:16 UTC, merged