Hw04 is complete
IvanSkripnikov/otus_go_homework pull request #4
Opened 2023-09-12 08:46 UTC by IvanSkripnikov

2023-09-15 04:04 UTC, vladislavmass requested changes
Хорошее начало. Радует что написано много тестов. Но в коде есть делающая размер кэша равным capacity-1

2023-09-15 04:04 UTC, hungry-honeybadger commented on hw04_lru_cache/cache.go
> +func (elem *lruCache) Set(key Key, value interface{}) bool {
Имя elem не очень хорошо подходит для ресивера так как складывается впечатление что это элемент кэша а не сам кэш.

2023-09-15 04:04 UTC, hungry-honeybadger commented on hw04_lru_cache/cache.go
> +	if elem.queue.Len() <= elem.capacity {
Эту проверку лучше переместить в метод set.

2023-09-15 04:04 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +func (elem *lruCache) RemoveOverflowElements() {
Этот метод не входит в интерфейс Cache, поэтому его лучше сделать неэскопортируемым

2023-09-15 04:04 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	if elem.queue.Len() <= elem.capacity {
Данное условие будет держать кэш в состояние когда число элементов в нем на 1 меньше чем капасити, что нарушает условия задачи

2023-09-15 18:10 UTC, IvanSkripnikov commented on hw04_lru_cache/cache.go
> +func (elem *lruCache) Set(key Key, value interface{}) bool {
исправил

2023-09-15 18:10 UTC, IvanSkripnikov commented on hw04_lru_cache/cache.go
> +	if elem.queue.Len() <= elem.capacity {
исправил

2023-09-15 18:11 UTC, IvanSkripnikov commented on hw04_lru_cache/cache.go
> +func (elem *lruCache) RemoveOverflowElements() {
исправил

2023-09-16 05:02 UTC, vladislavmass approved these changes
Хорошая работа. Принято. 10/10

2023-09-16 05:02 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		if lruCache.queue.Len() > lruCache.capacity {
Такое расположение кода приводит к том, что хоть и на время но в кэшэ больше элементов чем должно быть. Поэтому с начало должно быть , если оно нужно а потом добавление

2023-09-16 06:10 UTC, merged