Hw05 is complete
IvanSkripnikov/otus_go_homework pull request #5
Opened 2023-09-17 12:04 UTC by IvanSkripnikov

2023-09-19 17:59 UTC, vladislavmass requested changes
Хорошее начало. радует наличие комментария в коде но хотелось бы их видеть побольше. Работу принять немого, так как есть несколько потенциальных паник

2023-09-19 17:59 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	tasksCh := make(chan Task, n)
Делать канал неизвестного размера не очень хорошая идея

2023-09-19 17:59 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +		errorTaskCh <- task()
А если task=nil , то будет паника

2023-09-19 17:59 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +			return ErrErrorsLimitExceeded
Ошибка вернулась. Вызывающий код узнал что произошла ошибка. В это время воркеры продолжают работать и выполнять таски так как Producer продолжает работу, и как только кто то попытается записать в закрытый канал `errorTaskCh` будет паника

2023-09-20 10:02 UTC, IvanSkripnikov commented on hw05_parallel_execution/run.go
> +			return ErrErrorsLimitExceeded
поправил

2023-09-20 10:03 UTC, IvanSkripnikov commented on hw05_parallel_execution/run.go
> +		errorTaskCh <- task()
поправил

2023-09-20 10:03 UTC, IvanSkripnikov commented on hw05_parallel_execution/run.go
> +	tasksCh := make(chan Task, n)
поправил

2023-09-20 14:53 UTC, vladislavmass requested changes
Проблема с паникой при условии что task= nil решена. Остальные проблемы остались.

2023-09-20 14:53 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	tasksCh := make(chan Task, tasksCount)
Тоже самое. Делать канал неизвестного размера не самая хорошая затея. В идеале тут было бы использовать небуферизированный канал

2023-09-20 14:53 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	mu.Lock()
Данный лок не имеет никакого смысла. Так как он будет сразу же снят

2023-09-21 17:00 UTC, IvanSkripnikov commented on hw05_parallel_execution/run.go
> +	mu.Lock()
убрал

2023-09-21 17:01 UTC, IvanSkripnikov commented on hw05_parallel_execution/run.go
> +	tasksCh := make(chan Task, tasksCount)
поправил

2023-09-21 17:01 UTC, IvanSkripnikov commented on hw05_parallel_execution/run.go
> +			return ErrErrorsLimitExceeded
снова поправил

2023-09-21 18:13 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +func taskProducer(tasks []Task, tasksCh chan Task) {
Эта функция должна закончить свою работу если произошло больше чем m ошибок, но сейчас она этого не делает

2023-09-21 18:15 UTC, vladislavmass requested changes
Стало лучше, но у нас все еще есть проблемы с функцией taskProducer

2023-09-21 18:52 UTC, IvanSkripnikov commented on hw05_parallel_execution/run.go
> +func taskProducer(tasks []Task, tasksCh chan Task) {
поправил

2023-09-22 03:22 UTC, vladislavmass approved these changes
Хорошая работа. Принято. 7/10.-3 бала за запутанный код который можно упростить и за малое количество тестов.

2023-09-30 12:25 UTC, merged