Hw08 envdir tool
IvanSkripnikov/otus_go_homework pull request #8
Opened 2023-10-29 13:40 UTC by IvanSkripnikov

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-10-31 19:57 UTC, vladislavmass requested changes
Хорошая работа. Принято.

2023-10-31 19:57 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +		// убираем пробельные символы с краёв строки
Комментарии не соответствует действительности. Этот метод убирает не только пробелы, но и табуляцию

2023-10-31 19:57 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +	if info.Size() == 0 {
Этот методы лучше все таки было бы разместить в методе ReadDir. Так как пустой файл мы вс таки не пропустили, а обработали и приняли решение удалить переменную среды

2023-11-05 13:39 UTC, IvanSkripnikov commented on hw08_envdir_tool/env_reader.go
> +		// убираем пробельные символы с краёв строки
поправил комментарий

2023-11-05 13:40 UTC, IvanSkripnikov commented on hw08_envdir_tool/env_reader.go
> +	if info.Size() == 0 {
перенёс в ReadDir

2023-11-06 12:49 UTC, vladislavmass approved these changes

2023-11-06 12:50 UTC, merged